#!/bin/sh
set -e

# shellcheck source=/dev/null
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

echo "Running cargo fmt --check..."
cargo fmt --check

echo "Running cargo clippy..."
cargo clippy -- -D warnings
